#!/usr/bin/env python3
import sys
import os
import io

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow is required. Run 'pip install Pillow'")
    sys.exit(1)

def main():
    if len(sys.argv) < 3:
        print("Usage: import_boot_logo.py <input_image> <output_rust_file.rs>")
        sys.exit(1)

    in_file = sys.argv[1]
    out_file = sys.argv[2]
    
    if not os.path.exists(in_file):
        print(f"File not found: {in_file}")
        sys.exit(1)
        
    img = Image.open(in_file).convert("RGBA")

    print(f"Processing image...")
    img.thumbnail((600, 300), Image.Resampling.LANCZOS)
    w, h = img.size

    with open(out_file, "w") as f:
        f.write(f"// Auto-generated by tools/import_boot_logo.py\n")
        f.write(f"pub const LOGO_W: usize = {w};\n")
        f.write(f"pub const LOGO_H: usize = {h};\n")
        f.write(f"pub const LOGO_PIXELS: [u32; {w * h}] = [\n")
        
        pixels = img.load()
        for y in range(h):
            f.write("    ")
            for x in range(w):
                r, g, b, a = pixels[x, y]
                # blend background (black background if a == 0)
                if a == 0:
                    hex_color = 0x0
                else:
                    hex_color = (b) | (g << 8) | (r << 16) | (a << 24)
                f.write(f"0x{hex_color:08x}, ")
            f.write("\n")
            
        f.write("];\n")

    print(f"Successfully generated {out_file}.")

if __name__ == '__main__':
    main()
